version: '3.8'
services:
  mysqldb:
   container_name: mysqldb
   image: mysql
   ports:
    - "3306:3306"
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: openeye
    #MYSQL_USER: root
    #MYSQL_PASSWORD: root
   volumes:
      - ./data:/var/lib/mysql
   networks:
      - springboot-mysql-net
  openeyeattendanceservice:
    container_name: openeyeattendanceservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      mysqldb:
        condition: service_started
      openeyeserviceregistry:
        condition: service_started
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb/openeye?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - eureka.client.service-url.defaultZone=http://openeyeserviceregistry:8761/eureka/
      - eureka.client.enabled=true
      - eureka.host=openeyeserviceregistry
      - eureka.instance.preferIpAddress=false
      - eureka.instance.hostname=localhost
     
    networks:
      - springboot-mysql-net
      - springboot-net
    restart: on-failure

networks:
  springboot-mysql-net:
    driver: bridge