management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
      
     
resilience4j:
  circuitbreaker:
    instances:
      employeeResilience4j:
        base-config: employee
        
    configs:
      employee:
        register-health-indicator: true
        sliding-window-type: count-based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-duration-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10
        wait-duration-in-open-state: 10
        slow-call-rate-threshold: 2
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
      
server:
  port: 8082
spring:
  application:
    name: ATTENDANCE-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    url: jdbc:mysql://mysqldb/openeye?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost    
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/
  server:
    waitTimeInMsWhenSyncEmpty: 0